### PR TITLE
Add Chinese localization

### PR DESCRIPTION
**Pull request by sunxyw**
Please do not merge it, as it is not yet complete.
Update: It is completed now.

### CODE REVIEW

**Comment by sunxyw** [comment]
Chinese localization is complete.

**Comment by sunxyw** [comment]
> Also, should the game names itself, for example Europa Universalis 4, also be translatable?

I think yes.
Because they have official (or widely recognized) Chinese names. If it can be translated, it should be more friendly to Chinese users.

**Comment by crschnick** [comment]
I added a few more translatable strings in acfc54f. I think once these are translated, we can merge this PR

**Comment by crschnick** [comment]
I just released a new update that includes your translations.

**Pull request merged**
