### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hartmark**
Added link to aur-package

### CODE REVIEW

**Comment by crschnick** [comment]
Oh wow, did you create this package?

**Comment by crschnick** [comment]
Looking at it, it is an interesting implementation, I didn't even know that you can just publish .deb packages with tar like that.

One thing to note here is that the `java-runtime` dependency is not needed, as the runtime is bundled. Furthermore, many theoretical dependencies are purposefully not included in the .deb as that has caused problems previously. 

Moreover, the .deb version comes with the included auto-updater found at https://github.com/crschnick/pdxu_launcher, which does not support updating itself in that case as it only knows .deb and .rpm updates. So I think it should be updated to use the portable download, unzip it, and manually register the .desktop files.

Coincidentally, I created my first AUR package like a week ago, so you can add me as a maintainer: https://aur.archlinux.org/account/crschnick

**Comment by hartmark** [comment]
Yes, I created the package 😎

It's pretty cool how easy it is to create an aur-package.

The dependencies I just added so the namcap command doesn't complain. I haven't been coding Java for years so I just went with that without further analysis.

I can imagine some cleaning of the dependencies can be done with knowledge of the code.

I often make a -git package but were thinking that just going with a -deb would be faster as it would be a bit trickier to find out how to build it.

You can look at my aut user on the -git packages for inspiration.

I can give some quick commands that have helped me much with creating packages.

**Comment by hartmark** [comment]
I have added you as co-maintainer.

Quick rundown of commands that have helped me creating packages.

`git -c init.defaultbranch=master clone ssh://aur@aur.archlinux.org/pdx-unlimiter-deb.git`
where you just replace pdx-unlimiter-deb with the package-name

`makepkg -si`
And when it asks for sudo password I just press ctrl-c, then I have the package I can analyze its dependencies and check contents etc.

`namcap pdx-unlimiter-bin-2.13.2-1-x86_64.pkg.tar.zst`
Analyze the aur-package and prints out missing dependencies and other usual mistakes.

`namcap PKGBUILD`
Checks so that your PKGBUILD is sane

`makepkg --printsrcinfo > .SRCINFO`
Just remember doing this command before committing your changes as this file is used for the aur database for search.

Then I also use this .gitignore file so any generated files doesn't get added to the aur git repo
```
*
!.gitignore
!.SRCINFO
!PKGBUILD

```

Hope that helps and just poke me if want me to test any aur-packages or have any other questions.

**Comment by crschnick** [comment]
So, is it possible to rename this package? Because if it no longer uses the deb as base, the name is kinda wrong.

**Comment by crschnick** [comment]
Yeah let me see what I can come up with here

**Comment by crschnick** [comment]
Sorry for taking so long to respond to this, but I finally managed to find some time and provide a proper AUR package: https://aur.archlinux.org/packages/pdx-unlimiter . I had to change the package structure from your version to use the portable releases to avoid the bundled pdxu self-updater becoming confused when trying to install a new update.

I added you as a maintainer, so you can fix anything I didn't do properly or push any other changes.

**Comment by hartmark** [comment]
Cool, l'll check out your updated version when I get the time

**Comment by crschnick** [comment]
Would you be willing to maintain this package? I.e. update it every couple months when a new release of pdxu comes out.

Furthermore, you could take a look at the declared dependencies of the .deb package and figure out the appropriate packages to list under the depends entry. I didn't really spend any time with that as for the deb package that list is automatically generated by the java packager. I guess you have to ignore namcap complaining about some java related things and have to think more by yourself.

**Comment by hartmark** [comment]
Sure I'll try my best to maintain the packages ;)

**Comment by hartmark** [comment]
I have pushed some fixes to both my old -deb package with adding the desktop launcher and added checksums for the zip file in your new package.

Keep up the good work.

**Comment by crschnick** [comment]
I will merge this, that way you will be listed as a contributor automatically. Then I will update the link to point to the new package

**Comment by crschnick** [comment]
I recently pushed a new release, so you could try out how the actual release process of bumping up the versions and checksums works out for you

**Comment by hartmark** [comment]
Thanks for the ping, I have been having little free time lately so I haven't been able to look into this.

I have bumped the version on the AUR package and it seems to be working fine now.

However it seems that the deb-link on the release is on older version.
https://github.com/crschnick/pdx_unlimiter/releases/tag/2.13.5

I think I'll remove the pdx-unlimiter-deb as it seems to offer no any additional benefits.

**Comment by crschnick** [comment]
The deb download is only the launcher from https://github.com/crschnick/pdxu_launcher. That one is responsible for the automatic updates and installing the actual pdxu downloads. In retrospect this separate launcher wasn't really needed but back when I created it I had no idea what I was doing.

**Comment by crschnick** [comment]
There is a new pdxu release available

**Comment by hartmark** [comment]
Thanks for the heads up. I'll try get it bumped when I get the chance.

**Pull request merged**
